### PR TITLE
SUL23-125 | @jdwjdwjdw | Update branch content type to include center functionality

### PR DESCRIPTION
**Pull request by jdwjdwjdw**
# READY FOR REVIEW

# Summary
- [SUL23-125](https://stanfordits.atlassian.net/browse/SUL23-125): FE-DEV | Update branch content type to include center functionality

# Review By (Date)
- When convenient

# Steps to Test

1. Checkout branch or view [preview](https://deploy-preview-52--stanford-library.netlify.app/)
2. Generate branch locations of both `branch` and `center` type, or view preview examples for a [branch](https://deploy-preview-52--stanford-library.netlify.app/libraries/sws-test-323-example-branch-academy-hall) and [center](https://deploy-preview-52--stanford-library.netlify.app/libraries/branch-location-acsi-consectetuer-enim-exerci)
3. Confirm that they appear as specified (if Branch Page: site-visitor display will include custom page header/title with feature image and drop-down for hours. if Center Page: site-visitor display will be that of a Basic Page)
4. Review code 🍔 

[SUL23-125]: https://stanfordits.atlassian.net/browse/SUL23-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pookmish** [comment]
Looks like the layout paragraphs aren't getting the correct column layout functionality. https://deploy-preview-52--stanford-library.netlify.app/libraries/sws-test-327-example-center

**Comment by pookmish** [comment]
Also, i just reviewed SiteImprove report. There's currently no `h1` tag on the branch/center pages. Please see how that's done on other content types

**Comment by jdwjdwjdw** [comment]
> Also, i just reviewed SiteImprove report. There's currently no `h1` tag on the branch/center pages. Please see how that's done on other content types

Can you clarify this? I'm seeing an `h1` tag for the branch/center pages currently.
Screen Shot 2023-02-27 at 4 29 28 PM

**Comment by pookmish** [comment]
> Can you clarify this? I'm seeing an `h1` tag for the branch/center pages currently.

After I reviewed a little closer, there is an `h1` heading, but not from server side rendering. try this `wget -O test.html https://library-netlify.stanford.edu/sample-content/academy-hall-srwc` then review the test.html page to see there is no `h1`. If you aren't sure, I can try to review. to point you in the right direction: [on this line](https://github.com/SU-SWS/sulgryphon-nextjs/blob/1.x/src/components/nodes/node-sul-library.tsx#L38) if the browser hasn't collected the branch's hours, it won't return any header. You should move that conditional part to just the hours display/dropdown.

**Comment by jdwjdwjdw** [comment]
> > Can you clarify this? I'm seeing an `h1` tag for the branch/center pages currently.
> 
> After I reviewed a little closer, there is an `h1` heading, but not from server side rendering. try this `wget -O test.html https://library-netlify.stanford.edu/sample-content/academy-hall-srwc` then review the test.html page to see there is no `h1`. If you aren't sure, I can try to review. to point you in the right direction: [on this line](https://github.com/SU-SWS/sulgryphon-nextjs/blob/1.x/src/components/nodes/node-sul-library.tsx#L38) if the browser hasn't collected the branch's hours, it won't return any header. You should move that conditional part to just the hours display/dropdown.

Thanks - how about now? I'm now seeing the `h1's` when I view the page source at https://deploy-preview-52--stanford-library.netlify.app/sample-content/academy-hall-srwc

**Review by pookmish — APPROVED** [review]
Thanks. Looks good to me.

**Pull request merged**
