### PR TITLE
SUL23 36 Style Basic page and paragraphs

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Styled the different paragraph types in the basic page
- fixed various wysiwyg markup issues

# Need Review By (Date)
- :shrug: 

# Urgency
- medium

# Steps to Test
1. checkout this branch
2. `yarn dev`
3. Create a basic page
4. populate it with any of the paragraph types except lists & teasers
5. compare the results to an existing drupal site.

<a href="https://gitpod.io/#https://github.com/SU-SWS/sulgryphon-nextjs/pull/7"></a>

### CODE REVIEW

**Comment by jdwjdwjdw** [comment]
Bug I found during my review - looks like adding preformatted text `<pre>` in a text area paragraph breaks the page (see attached for the 3 errors I'm seeing). I recreated it outside of this branch, so it's not directly caused by any of your changes here. See related link at https://nextjs.org/docs/messages/react-hydration-error
Screen Shot 2022-10-27 at 2 05 55 PM
Screen Shot 2022-10-27 at 2 06 02 PM
Screen Shot 2022-10-27 at 2 06 06 PM

**Comment by pookmish** [comment]
After working around things, it turned out that the HTML from drupal contained some line breaks that React didn't like. I put up a partner PR https://github.com/SU-SWS/ace-sulgryphon/pull/12. Try with that PR.

**Comment by pookmish** [comment]
Neat thing about gitpod: if the backend has a branch with the same name, gitpod will checkout the same branch for each repo. Keep that in mind if you have to make any changes on the drupal side.

**Comment by jdwjdwjdw** [comment]
> After working around things, it turned out that the HTML from drupal contained some line breaks that React didn't like. I put up a partner PR [SU-SWS/ace-sulgryphon#12](https://github.com/SU-SWS/ace-sulgryphon/pull/12). Try with that PR.

That worked, thanks!

**Pull request merged**
