### PR TITLE
Remove node cache to improve cache invalidation for config pages

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Remove node-cache implementations
- We are using the on demand cache invalidation on the route `/api/revalidate` but this isn't clearing the node-cache. We don't really need it anymore anyways. We can just eliminate it.

### CODE REVIEW

**Comment by imonroe** [comment]
Ok, so I think I see what you're doing here, but a couple of things.
Something in the main menu styling has changed such that `:hover` and `:active` states seem to make the text disappear.  I think it's turning the text white.
But more to the point, it doesn't seem to fix the problem with the Global Message revalidation.
Try this: 
- while on this branch, with the front-end running, set up a Global Message in Drupal.  Enable it, save it.
- Refresh the front end page in your browser.  Note that the Global Message does not appear.
- do a GET for http://localhost:3000/api/revalidate/?slug=/tags/config-pages&secret=xxxxx 
- verify that it has cleared out the config-pages cache.
- Refresh the page on the front end.  Note the Global Message now appears.  It works the other direction too; if you then disable the global message, it will still appear in the front end until you do a manual revalidation.

I looked in the `next` module on the drupal side, and it looks set up to invalidate the config-pages cache tag correctly: 
image

And when I do the revalidation manually, it works immediately.  But it does not work when the config page is saved in the admin interface, which would be the expected behavior.

**Comment by imonroe** [comment]
maybe this is something that needs to be fixed on the Drupal side, rather than the Next side.  Maybe with an event listener on the global message update triggering the on-demand revalidation?

**Comment by pookmish** [comment]
The config page invalidation works correctly as it should in both drupal and on this branch. I have no issues at all when editing/disabling/enabling the global messages banner. I even put in a console.log on the api/revalidate route and it shows the correct cache tags are being invalidated. I am confident in the removal of node cache fixing the issue.
If you want to test this out, make sure you are running `yarn preview`, not `yarn dev`. The latter behaves differently than the former in terms of cache functionality. This PR will solve the issues

**Comment by pookmish** [comment]
As for the menu styling, yeah I'll fix that real quick.

**Comment by imonroe** [comment]
Ok, so I got the same results on my local with `yarn preview` as well as `yarn dev` (didn't work).  I tried it using both chrome and firefox with no differences.
I tried it on Gitpod, and I got the same results there (didn't work), presumably because it's doing a `yarn dev` for those environments.
So then I tried it on the Vercel preview build, and there is worked exactly as expected.

I'm not sure what's up with that.  I'm going to do some troubleshooting on my local and see if something is messed up.

Anyways, since it works on Vercel, that's the important part.

**Review by imonroe — APPROVED** [review]

**Pull request merged**
