### PR TITLE
Keyword search filter stubbed out

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW
- Updated the styling to match the designs.

#TO TEST 
- Add a person list on a basic page.
- Verify the search box matches the design in Figma.
- Review code.
[- SUL23-503](https://stanfordits.atlassian.net/browse/SUL23-503)

# Summary
- Stubbed out keyword filtering functionality.
- Needs styling - done.

### CODE REVIEW

**Comment by jenbreese** [comment]
@imonroe would you take a look at this PR? Mike did the search part and I styled it. Thank you!

**Comment by imonroe** [comment]
I see the search field and the toggles, but "All Specialists" appears twice.
image

When I do a search with the first "all specialists" chosen, it works as I'd expect.  When I toggle the second one, it doesn't return any  results for the search.  Perhaps because of limited data on the Dev server?  I also notice that I can toggle the second "all specialists" and "technical specialists" at the same time, and either way, it returns no results.

image

**Review by imonroe — APPROVED** [review]
This works for me in the vercel preview.

**Comment by jenbreese** [comment]
@imonroe I had trouble merging this all together.  Can you take another look please?

**Comment by imonroe** [comment]
Seems to work for me here: https://su-library-98tuomnjh-stanford-libraries.vercel.app/test-list-page

**Pull request merged**
